<?php

/**
 * @file
 * Contains graphql_easy.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function graphql_easy_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the graphql_easy module.
    case 'help.page.graphql_easy':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Extends the API provided by drupal/graphql with a cleaner API along with a library of resolver plugins and dataproviders.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function graphql_easy_theme() {
  return [
    'graphql_easy' => [
      'render element' => 'children',
    ],
  ];
}
